spring:
  datasource:
    url: jdbc:h2:mem:feedDb
    username: test
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true
  mvc:
    pathmatch:
        matching-strategy: ant-path-matcher

springdoc:
    swagger-ui:
        path: /swagger-ui.html